apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - auth
  - auth-mongo
  - tickets
  - tickets-mongo
  - orders
  - orders-mongo
  - client
  - gateway
  - event-bus
  - expiration
  - redis