apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ticketing-prod

resources:
  - namespace.yaml
  - ../../base
  - app-config.yaml
  - ingress.yaml

patches:
  - path: nats-patch.yaml